using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SnyderIS.sCore.Exi.Implementation.Widget.FluentWizard;
using SnyderIS.sCore.Exi.Implementation.Widget;

namespace IQI.Intuition.Exi.Configuration.QIDashboard
{
    public static class WarningConfig
    {

        public static WidgetGroupBuilder Build(WizardBuilder src)
        {
            return src.BeginGroup()
                   .Named("Warnings And Alerts")
                   .WithDescription("View facility and patient alerts generated by the system.")
                   .BeginWidget()
                       .Named("Warning list")
                       .WithDescription("List of recent warnings. Includes the ability to hide warnings already viewed.")
                       .IncludeRenderer<Renderers.QIDashboard.Alerts.WarningList>()
                           .Named("List")
                           .WithDescription("List of recent warnings. Includes the ability to hide warnings already viewed.")
                           .EndRenderer()
                       .SetDataSource<DataSources.QIDashboard.Alerts.DataSource>()
                   .EndWidget();
        }
    }
}
